/// A utility class for mapping Bluetooth GATT UUIDs to human-readable names.
class BluetoothUuidMapper {
  /// Maps Bluetooth SIG Service UUIDs to their official names.
  static const Map<String, String> _services = {
    '1800': 'Generic Access',
    '1801': 'Generic Attribute',
    '1802': 'Immediate Alert',
    '1803': 'Link Loss',
    '1804': 'Tx Power',
    '1805': 'Current Time',
    '1806': 'Reference Time Update',
    '1807': 'Next DST Change',
    '1808': 'Glucose',
    '1809': 'Health Thermometer',
    '180A': 'Device Information',
    '180D': 'Heart Rate',
    '180E': 'Phone Alert Status',
    '180F': 'Battery Service',
    '1810': 'Blood Pressure',
    '1811': 'Alert Notification Service',
    '1812': 'Human Interface Device',
    '1813': 'Scan Parameters',
    '1814': 'Running Speed and Cadence',
    '1815': 'Automation IO',
    '1816': 'Cycling Speed and Cadence',
    '1818': 'Cycling Power',
    '1819': 'Location and Navigation',
    '181A': 'Environmental Sensing',
    '181B': 'Body Composition',
    '181C': 'User Data',
    '181D': 'Weight Scale',
    '181E': 'Bond Management Service',
    '181F': 'Continuous Glucose Monitoring',
    '1820': 'Internet Protocol Support Service',
    '1821': 'Indoor Positioning',
    '1822': 'Pulse Oximeter Service',
    '1823': 'HTTP Proxy Service',
    '1824': 'Transport Discovery Service',
    '1825': 'Object Transfer Service',
    '1826': 'Fitness Machine Service',
    '1827': 'Mesh Provisioning Service',
    '1828': 'Mesh Proxy Service',
    '1829': 'Reconnection Configuration',
  };

  /// Maps Bluetooth SIG Characteristic UUIDs to their official names.
  static const Map<String, String> _characteristics = {
    '2A00': 'Device Name',
    '2A01': 'Appearance',
    '2A02': 'Peripheral Privacy Flag',
    '2A03': 'Reconnection Address',
    '2A04': 'Peripheral Preferred Connection Parameters',
    '2A05': 'Service Changed',
    '2A06': 'Alert Level',
    '2A07': 'Tx Power Level',
    '2A08': 'Date Time',
    '2A09': 'Day of Week',
    '2A0A': 'Day Date Time',
    '2A0C': 'Exact Time 256',
    '2A0D': 'DST Offset',
    '2A0E': 'Time Zone',
    '2A0F': 'Local Time Information',
    '2A11': 'Time with DST',
    '2A12': 'Time Accuracy',
    '2A13': 'Time Source',
    '2A14': 'Reference Time Information',
    '2A16': 'Time Update Control Point',
    '2A17': 'Time Update State',
    '2A18': 'Glucose Measurement',
    '2A19': 'Battery Level',
    '2A1C': 'Temperature Measurement',
    '2A1D': 'Temperature Type',
    '2A1E': 'Intermediate Temperature',
    '2A21': 'Measurement Interval',
    '2A22': 'Boot Keyboard Input Report',
    '2A23': 'System ID',
    '2A24': 'Model Number String',
    '2A25': 'Serial Number String',
    '2A26': 'Firmware Revision String',
    '2A27': 'Hardware Revision String',
    '2A28': 'Software Revision String',
    '2A29': 'Manufacturer Name String',
    '2A2A': 'IEEE 11073-20601 Regulatory Certification Data List',
    '2A2B': 'Current Time',
    '2A2C': 'Magnetic Declination',
    '2A31': 'Scan Refresh',
    '2A37': 'Heart Rate Measurement',
    '2A38': 'Body Sensor Location',
    '2A39': 'Heart Rate Control Point',
    '2A3F': 'Alert Status',
    '2A40': 'Ringer Control Point',
    '2A41': 'Ringer Setting',
    '2A42': 'Alert Category ID Bit Mask',
    '2A43': 'Alert Category ID',
    '2A44': 'Alert Notification Control Point',
    '2A45': 'Unread Alert Status',
    '2A46': 'New Alert',
    '2A47': 'Supported New Alert Category',
    '2A48': 'Supported Unread Alert Category',
    '2A49': 'Blood Pressure Feature',
    '2A4A': 'HID Information',
    '2A4B': 'Report Map',
    '2A4C': 'HID Control Point',
    '2A4D': 'Report',
    '2A4E': 'Protocol Mode',
    '2A4F': 'Scan Interval Window',
    '2A50': 'PnP ID',
    '2A51': 'Glucose Feature',
    '2A52': 'Record Access Control Point',
    '2A53': 'CSC Measurement',
    '2A54': 'CSC Feature',
    '2A55': 'Sensor Location',
    '2A5A': 'Aggregate',
    '2A5B': 'CSC Measurement',
    '2A5C': 'CSC Feature',
    '2A5D': 'Sensor Location',
    '2A63': 'Cycling Power Measurement',
    '2A64': 'Cycling Power Vector',
    '2A65': 'Cycling Power Feature',
    '2A66': 'Cycling Power Control Point',
    '2A67': 'Location and Speed',
    '2A68': 'Navigation',
    '2A69': 'Position Quality',
    '2A6A': 'Latitude',
    '2A6B': 'Longitude',
    '2A6C': 'Elevation',
    '2A6D': 'Pressure',
    '2A6E': 'Temperature',
    '2A6F': 'Humidity',
    '2A70': 'True Wind Speed',
    '2A71': 'True Wind Direction',
    '2A72': 'Apparent Wind Speed',
    '2A73': 'Apparent Wind Direction',
    '2A74': 'Gust Factor',
    '2A75': 'Pollen Concentration',
    '2A76': 'UV Index',
    '2A77': 'Irradiance',
    '2A78': 'Rainfall',
    '2A79': 'Wind Chill',
    '2A7A': 'Heat Index',
    '2A7B': 'Dew Point',
    '2A7D': 'Descriptor Value Changed',
    '2A7E': 'Aerobic Heart Rate Lower Limit',
    '2A7F': 'Aerobic Threshold',
    '2A80': 'Age',
    '2A81': 'Anaerobic Heart Rate Lower Limit',
    '2A82': 'Anaerobic Heart Rate Upper Limit',
    '2A83': 'Anaerobic Threshold',
    '2A84': 'Aerobic Heart Rate Upper Limit',
    '2A85': 'Date of Birth',
    '2A86': 'Date of Threshold Assessment',
    '2A87': 'Email Address',
    '2A88': 'Fat Burn Heart Rate Lower Limit',
    '2A89': 'Fat Burn Heart Rate Upper Limit',
    '2A8A': 'First Name',
    '2A8B': 'Five Zone Heart Rate Limits',
    '2A8C': 'Gender',
    '2A8D': 'Heart Rate Max',
    '2A8E': 'Height',
    '2A8F': 'Hip Circumference',
    '2A90': 'Last Name',
    '2A91': 'Maximum Recommended Heart Rate',
    '2A92': 'Resting Heart Rate',
    '2A93': 'Sport Type for Aerobic and Anaerobic Thresholds',
    '2A94': 'Three Zone Heart Rate Limits',
    '2A95': 'Two Zone Heart Rate Limits',
    '2A96': 'Weight',
    '2A97': 'Database Change Increment',
    '2A98': 'User Index',
    '2A99': 'Body Composition Feature',
    '2A9A': 'Body Composition Measurement',
    '2A9B': 'Weight Measurement',
    '2A9C': 'Weight Scale Feature',
    '2A9D': 'User Control Point',
    '2A9E': 'Magnetic Flux Density - 2D',
    '2A9F': 'Magnetic Flux Density - 3D',
    '2AA0': 'Language',
    '2AA1': 'Barometric Pressure Trend',
    '2AA2': 'Bond Management Control Point',
    '2AA3': 'Bond Management Feature',
    '2AA4': 'Central Address Resolution',
    '2AA5': 'CGM Measurement',
    '2AA6': 'CGM Feature',
    '2AA7': 'CGM Status',
    '2AA8': 'CGM Session Start Time',
    '2AA9': 'CGM Session Run Time',
    '2AAA': 'CGM Specific Ops Control Point',
    '2AAB': 'HTTP Entity Body',
    '2AAC': 'HTTP Extension Code',
    '2AAD': 'HTTP Headers',
    '2AAE': 'HTTP Status Code',
    '2AAF': 'HTTPS Security',
    '2AB0': 'HTTP Control Point',
    '2AB1': 'HTTP Status Code',
    '2AB2': 'HTTP Headers',
    '2AB3': 'HTTP Entity Body',
    '2AB4': 'HTTP Extension Code',
    '2AB5': 'HTTPS Security',
    '2AB6': 'TDS Control Point',
    '2AB7': 'OTS Feature',
    '2AB8': 'object name',
    '2AB9': 'object type',
    '2ABA': 'object size',
    '2ABB': 'object first-created',
    '2ABC': 'object last-modified',
    '2ABD': 'object ID',
    '2ABE': 'object properties',
    '2ABF': 'object action control point',
    '2AC0': 'object list control point',
    '2AC1': 'object list filter',
    '2AC2': 'object changed',
    '2ACC': 'Fitness Machine Feature',
    '2ACD': 'Treadmill Data',
    '2ACE': 'Cross Trainer Data',
    '2ACF': 'Step Climber Data',
    '2AD0': 'Stair Climber Data',
    '2AD1': 'Rower Data',
    '2AD2': 'Indoor Bike Data',
    '2AD3': 'Training Status',
    '2AD4': 'Supported Speed Range',
    '2AD5': 'Supported Inclination Range',
    '2AD6': 'Supported Resistance Level Range',
    '2AD7': 'Supported Heart Rate Range',
    '2AD8': 'Supported Power Range',
    '2AD9': 'Fitness Machine Control Point',
    '2ADA': 'Fitness Machine Status',
  };

  /// Normalizes a UUID string to a common format for lookup.
  /// Supports 16-bit, 32-bit, and 128-bit Bluetooth SIG UUIDs.
  static String normalize(String uuid) {
    String normalized = uuid.replaceAll('-', '').toUpperCase();
    if (normalized.length == 32) {
      if (normalized.endsWith('00001000800000805F9B34FB')) {
        normalized = normalized.substring(0, 8);
        if (normalized.startsWith('0000')) {
          normalized = normalized.substring(4);
        }
      }
    }
    return normalized;
  }

  /// Returns the human-readable name of a Bluetooth GATT Service.
  /// Returns "Manufacturer Service" if the UUID is not recognized.
  static String getServiceName(String uuid) {
    final normalized = normalize(uuid);
    return _services[normalized] ?? 'Manufacturer Service';
  }

  /// Returns the human-readable name of a Bluetooth GATT Characteristic.
  /// Returns "Manufacturer Characteristic" if the UUID is not recognized.
  static String getCharacteristicName(String uuid) {
    final normalized = normalize(uuid);
    return _characteristics[normalized] ?? 'Manufacturer Characteristic';
  }

  /// Returns true if the Service UUID is a standard Bluetooth SIG UUID.
  static bool isStandardService(String uuid) {
    final normalized = normalize(uuid);
    return _services.containsKey(normalized);
  }

  /// Returns true if the Characteristic UUID is a standard Bluetooth SIG UUID.
  static bool isStandardCharacteristic(String uuid) {
    final normalized = normalize(uuid);
    return _characteristics.containsKey(normalized);
  }
}
